[book]
title = "Learn Operating Systems with Go"
authors = ["Tej Chajed"]
language = "en"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/tchajed/os-with-go"
additional-css = []
